<template>
  <div class="container">
    <div class="content">
      <div class="hi-and-name">
        <div class="hi-container">
          <span>Hi </span>
          <img src="~/assets/img/hand.png" class="hand wave" />
        </div>
        <div class="name-container">
          <span>, </span>
          <span>I’m </span>
          <span class="name">Federico</span>
          <span>, </span>
        </div>
      </div>
      <div class="description">
        a developer who
        <span class="secondary-highlight">loves</span>
        building
        <span class="secondary-highlight">great</span>
        products.
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'JumboTagLine',
}
</script>

<style scoped>
.container {
  display: flex;
  flex: 1.5;
  align-items: center;
  justify-content: center;

  font-weight: bold;
  font-size: 48px;
  line-height: 58px;
}

.content {
  max-width: 580px;
}

.hi-and-name {
  display: flex;
}

.hand {
  height: 48px;
  width: 48px;

  animation-name: wave-animation;
  animation-duration: 2.5s;
  animation-delay: 1s;
  transform-origin: 70% 70%;
  display: inline-block;
}

.hi-container {
  animation: hi-offset 4s cubic-bezier(0.23, 1, 0.32, 1) both;
}

.name {
  color: var(--accent-primary);
}

.name-container {
  animation: slide-in-blurred-right 1s cubic-bezier(0.23, 1, 0.32, 1) both;
  animation-delay: 2.5s;
}

.description {
  animation: slide-in-blurred-bottom 1.5s cubic-bezier(0.23, 1, 0.32, 1) both;
  animation-delay: 3.5s;
}

.secondary-highlight {
  color: var(--accent-secondary);
  text-decoration-line: underline;
}

/* Animation taken from https://jarv.is/notes/css-waving-hand-emoji/ */
@keyframes wave-animation {
  0% {
    transform: rotate(0deg);
  }
  10% {
    transform: rotate(14deg);
  } /* The following five values can be played with to make the waving more or less extreme */
  20% {
    transform: rotate(-8deg);
  }
  30% {
    transform: rotate(14deg);
  }
  40% {
    transform: rotate(-4deg);
  }
  50% {
    transform: rotate(10deg);
  }
  60% {
    transform: rotate(0deg);
  } /* Reset for the last half to pause */
  100% {
    transform: rotate(0deg);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-16 22:24:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-right
 * ----------------------------------------
 */
@keyframes slide-in-blurred-right {
  0% {
    transform: translateX(100px) scaleX(1.5) scaleY(0.2);
    transform-origin: 0% 50%;
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    transform: translateX(0) scaleY(1) scaleX(1);
    transform-origin: 50% 50%;
    filter: blur(0);
    opacity: 1;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-16 22:30:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-bottom
 * ----------------------------------------
 */
@keyframes slide-in-blurred-bottom {
  0% {
    transform: translateY(100px) scaleY(1.5);
    transform-origin: 50% 100%;
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    transform: translateY(0) scaleY(1);
    transform-origin: 50% 50%;
    filter: blur(0);
    opacity: 1;
  }
}

@keyframes hi-offset {
  0% {
    transform: translateX(200px);
    transform-origin: 50% 100%;
    filter: blur(40px);
    opacity: 0;
  }
  50% {
    transform: translateX(200px);
    filter: blur(0);
    opacity: 1;
  }
  100% {
    transform: translateX(0);
  }
}
</style>