<template>
  <div class="container">
    <div class="jumbo-image" @click="toggleTheme"></div>
  </div>
</template>

<script>
export default {
  name: 'JumboImage',
  methods: {
    toggleTheme() {
      const currentTheme = window.document.documentElement.dataset.theme
      if (currentTheme === 'light') {
        window.switchTheme('dark')
      } else {
        window.switchTheme('light')
      }
    },
  },
}
</script>

<style scoped>
.container {
  display: flex;
  align-items: center;
  justify-content: center;
  flex: 1;
  z-index: 2;
}

.jumbo-image {
  width: 530px;
  height: 580px;
  background-position: center center;
  background-size: contain;
  background-repeat: no-repeat;
  background-image: url('~assets/img/jumbo-image-light.png');

  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation-delay: 2s;

  cursor: pointer;
}

html[data-theme='dark'] .jumbo-image {
  background-image: url('~assets/img/jumbo-image-dark.png');
}

@media (max-width: 992px) {
  .container {
    flex: 1.5;
  }

  .jumbo-image {
    width: 55vw;
    height: 40vh;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-18 22:5:51
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>