<template>
  <div
    class="project-item-container"
    v-observe-visibility="{ callback: visibilityChanged, once: true }"
  >
    <a :href="imageLink" target="_blank" class="project-item-image-wrapper">
      <div
        class="project-item-image"
        :style="{ backgroundImage: `url('${image}')` }"
        :class="{ 'animate-left': visible }"
      ></div>
    </a>
    <div class="project-item-content" :class="{ 'animate-right': visible }">
      <h2 class="name">{{ name }}</h2>
      <p class="keywords">{{ joinedKeywords }}</p>
      <nuxt-content :document="project" />
      <div class="project-item-buttons">
        <ProjectButton :link="website" v-if="website" label="Website" />
        <ProjectButton :link="play" v-if="play" label="Play online" />
        <ProjectButton
          :link="github"
          v-if="github"
          label="GitHub"
          icon="github"
        />
        <ProjectButton
          :link="youtube"
          v-if="youtube"
          label="YouTube"
          icon="youtube"
        />
        <ProjectButton :link="gplay" v-if="gplay" label="Play Store" />
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ProjectItem',
  props: {
    image: String,
    name: String,
    keywords: Array,
    snippet: String,
    project: Object,
    website: String,
    github: String,
    youtube: String,
    play: String,
    gplay: String,
  },
  data: () => ({
    visible: false,
  }),
  methods: {
    visibilityChanged(isVisible) {
      this.visible = isVisible
    },
  },
  computed: {
    joinedKeywords() {
      if (!this.keywords) {
        return ''
      }

      return this.keywords.join(', ')
    },
    imageLink() {
      if (this.website) {
        return this.website
      }
      if (this.github) {
        return this.github
      }
      if (this.youtube) {
        return this.youtube
      }
      if (this.play) {
        return this.play
      }
      if (this.gplay) {
        return this.gplay
      }
      if (this.website) {
        return this.website
      }

      return ''
    },
  },
}
</script>

<style scoped>
.project-item-container {
  display: flex;
}

.project-item-content {
  flex: 1;
  display: flex;
  padding: 0;
  flex-direction: column;
}

.project-item-image-wrapper {
  flex: 1;
  filter: drop-shadow(0px 4px 15px rgba(0, 0, 0, 0.25));
}

.project-item-image {
  height: 300px;
  width: 300px;
  margin-right: 50px;
  box-sizing: border-box;
  border-radius: 12px;
  background-size: contain;
  background-position: center;
  background-repeat: no-repeat;
}

.project-item-buttons {
  display: flex;
}

.project-item-buttons > a {
  margin-right: 20px;
}

.name {
  font-weight: bold;
  font-size: 24px;
  line-height: 29px;
  margin-bottom: 5px;
  margin-top: 0;
}

.keywords {
  font-weight: bold;
  font-size: 12px;
  line-height: 15px;

  margin-top: 0;
  margin-bottom: 8px;

  color: var(--accent-primary);
}

.snippet {
  font-size: 15px;
  line-height: 22px;
  font-family: 'PT Serif';
}

.animate-left {
  animation: slide-in-blurred-left 1s cubic-bezier(0.23, 1, 0.32, 1) both;
}

.animate-right {
  animation: slide-in-blurred-right 1s cubic-bezier(0.23, 1, 0.32, 1) both;
}

@media (max-width: 992px) {
  .project-item-container {
    align-items: center;
    flex-direction: column;
  }

  .project-item-image {
    margin-right: 0;
    margin-bottom: 24px;
    height: 150px;
    background-size: cover;
    border-radius: 12px;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-24 21:57:10
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-right
 * ----------------------------------------
 */
@keyframes slide-in-blurred-right {
  0% {
    transform: translateX(200px);
    transform-origin: 0% 50%;
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    transform: translateX(0);
    transform-origin: 50% 50%;
    filter: blur(0);
    opacity: 1;
  }
}

@keyframes slide-in-blurred-left {
  0% {
    transform: translateX(-200px);
    transform-origin: 0% 50%;
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    transform: translateX(0);
    transform-origin: 50% 50%;
    filter: blur(0);
    opacity: 1;
  }
}
</style>