<template>
  <div
    class="regular-section-container"
    v-observe-visibility="{ callback: visibilityChanged, once: true }"
  >
    <div class="title-container" :class="{ 'animate-left': visible }">
      <ArrowLeft class="title-arrow" />
      <span>{{ title }}</span>
    </div>
    <div class="content-container" :class="{ 'animate-right': visible }">
      <div class="section-content">
        <slot></slot>
      </div>
    </div>
  </div>
</template>

<script>
import ArrowLeft from '~/assets/svg/arrow-left.svg?inline'

export default {
  name: 'RegularSection',
  props: {
    title: String,
  },
  components: {
    ArrowLeft,
  },
  data: () => ({
    visible: false,
  }),
  methods: {
    visibilityChanged(isVisible) {
      this.visible = isVisible
    },
  },
}
</script>

<style scoped>
.regular-section-container {
  display: flex;
  flex-direction: column;
  align-items: stretch;
  padding: 28px;
}

.title-container {
  display: flex;
  justify-content: center;

  font-style: normal;
  font-weight: bold;
  font-size: 28px;
  line-height: 34px;

  color: var(--accent-secondary);
  opacity: 0.01;
}

.title-arrow {
  margin-right: 8px;
}

.content-container {
  opacity: 0.01;
  margin-top: 62px;
}

.section-content {
  display: flex;
  flex-direction: column;

  max-width: 1000px;
  margin: auto;
}

.animate-left {
  animation: slide-in-blurred-left 1.5s cubic-bezier(0.23, 1, 0.32, 1) both;
}

.animate-right {
  animation: slide-in-blurred-right 1.5s cubic-bezier(0.23, 1, 0.32, 1) both;
}

@media (max-width: 992px) {
  .container {
    flex-direction: column;
  }

  .title-container {
    justify-content: flex-start;
    margin-left: -8px;
    margin-bottom: 24px;
  }

  .content-container {
    margin-top: 12px;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-24 21:57:10
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-right
 * ----------------------------------------
 */
@keyframes slide-in-blurred-right {
  0% {
    transform: translateX(200px);
    transform-origin: 0% 50%;
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    transform: translateX(0);
    transform-origin: 50% 50%;
    filter: blur(0);
    opacity: 1;
  }
}

@keyframes slide-in-blurred-left {
  0% {
    transform: translateX(-200px);
    transform-origin: 0% 50%;
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    transform: translateX(0);
    transform-origin: 50% 50%;
    filter: blur(0);
    opacity: 1;
  }
}
</style>