<template>
  <div class="container" @click="scroll">
    <span class="label">Scroll to know more</span>
    <div class="arrows">
      <RedArrow class="red arrow" />
      <YellowArrow class="yellow arrow" />
    </div>
  </div>
</template>

<script>
import YellowArrow from '~/assets/svg/arrow-down-yellow.svg?inline'
import RedArrow from '~/assets/svg/arrow-down-red.svg?inline'

export default {
  name: 'ScrollDownIndicator',
  components: { YellowArrow, RedArrow },
  methods: {
    scroll() {
      const headerElement = document.getElementById('header')
      const headerHeight = headerElement.getBoundingClientRect().height

      const aboutSection = document.getElementById('about-section')
      const elementPosition = aboutSection.getBoundingClientRect().top
      const offsetPosition = elementPosition + window.pageYOffset - headerHeight

      window.scrollTo({
        top: offsetPosition,
        behavior: 'smooth',
      })
    },
  },
}
</script>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  align-items: center;

  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation-delay: 5s;

  cursor: pointer;
}

.label {
  font-size: 14px;
  line-height: 17px;
  font-weight: bold;
  text-align: center;
  color: var(--accent-secondary);

  margin-bottom: 12px;

  animation: slide-bottom 2s infinite both;
  animation-delay: 0.2s;
}

.arrows {
  position: relative;
  width: 30px;
}

.arrow {
  position: absolute;
  animation: slide-bottom 2s infinite both;
}

.yellow {
  top: 0;
  left: -2px;
}

.red {
  top: 5px;
  animation-delay: 0.2s;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-19 21:15:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-bottom
 * ----------------------------------------
 */
@keyframes slide-bottom {
  0% {
    transform: translateY(0);
  }
  70% {
    transform: translateY(10px);
  }
  100% {
    transform: translateY(0);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-19 21:22:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>