<template>
  <div class="container">
    <div class="blurred red animate"></div>
    <div class="blurred yellow animate"></div>
    <div class="blurred blue animate"></div>
  </div>
</template>

<script>
export default {
  name: 'TheBackground',
}
</script>

<style scoped>
.container {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}

.blurred {
  filter: blur(50px);
  z-index: 0;
}

.animate {
  animation: rotate-center 120s linear infinite both;
}

.red {
  position: absolute;
  top: 25vh;
  left: -10vw;

  background-color: var(--accent-primary);
  opacity: 0.1;
  height: 450px;
  width: 450px;
}

.blue {
  position: absolute;
  top: 0;
  right: -10vw;

  background-color: var(--accent-secondary);
  opacity: 0.1;
  height: 450px;
  width: 450px;
}

.yellow {
  position: absolute;
  top: 75vh;
  left: 40vw;

  background-color: var(--accent-tertiary);
  opacity: 0.3;
  height: 450px;
  width: 450px;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-18 21:5:23
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
@keyframes rotate-center {
  0% {
    transform: rotate(0) translateX(0) translateY(0);
  }
  50% {
    transform: rotate(180deg) translateX(300px) translateY(300px);
  }
  100% {
    transform: rotate(360deg) translateX(0) translateY(0);
  }
}
</style>